---
apiVersion: v1
kind: Service
metadata:
  name: chatbot
spec:
  type: ClusterIP
  selector:
    app: chatbot
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot
  labels:
    app: chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot
  template:
    metadata:
      labels:
        app: chatbot
    spec:
      containers:
      - name: chatbot
        image: us-central1-docker.pkg.dev/REPLACEME/REPLACEME/app:latest